name: Release

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - next
      - alpha
      - beta

jobs:
  release:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # run before Set node , otherwise show Unable to locate executable file: pnpm error
      - name: Use just
      - uses: extractions/setup-just@v2

      - name: Use bun
      - uses: oven-sh/setup-bun@v2

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: just install

      - name: Build
        run: just build
      - name: Test
        run: just test
      - uses: codecov/codecov-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        # https://github.com/semantic-release/semantic-release/issues/2313
        # continue-on-error: true

      # - name: Publish to NPM
      #   run: pnpm publish --access public --no-git-checks
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      #     NPM_CONFIG_PROVENANCE: true
